create table habits (id serial primary key, name varchar ( 255 ) not null);
create table habits (id serial primary key, dailyHabit_Date date not null);
create table users (id serial primary key, nameUser varchar (255) not null, passwordUser varchar (150));
alter table dailyhabit add column id_user int not null;
alter table dailyhabit add column id_habit int not null;
alter table dailyhabit add column id_group int not null;
alter table users add column id_group int;
alter table habits add column id_group int;
create table groups (id serial primary key, namegroup varchar (255) not null);
select * from groups;